<a href="https://colab.research.google.com/github/steenbergen/DeepLearn/blob/main/convnet_time.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from numpy import array
from tensorflow import keras
from tensorflow.keras import layers

In [2]:
def split_sequence(sequence,steps):
  x, y = list(), list()
  for start in range(len(sequence)):
    end_index = start + steps
    if end_index > len(sequence) - 1:
      break
    sequence_x, sequence_y = sequence[start : end_index], sequence[end_index]
    x.append(sequence_x)
    y.append(sequence_y)
  return array(x), array(y)


In [3]:
raw_sequence = [100, 110, 120, 130, 140, 150, 160, 170, 180, 190]
steps = 3
x, y = split_sequence(raw_sequence, steps)
print(x)
print(y)

[[100 110 120]
 [110 120 130]
 [120 130 140]
 [130 140 150]
 [140 150 160]
 [150 160 170]
 [160 170 180]]
[130 140 150 160 170 180 190]


In [4]:
features = 1
x = x.reshape(x.shape[0], x.shape[1], features)
x.shape

(7, 3, 1)

In [9]:
input_shape = (steps, features)
model = keras.Sequential(
    [keras.Input(shape = input_shape),
     layers.Conv1D(filters = 64, kernel_size = 2, activation = "relu"),
     layers.MaxPooling1D(pool_size = 2),
     layers.Flatten(),
     layers.Dense(1)]
)
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d_2 (Conv1D)           (None, 2, 64)             192       
                                                                 
 max_pooling1d_2 (MaxPooling  (None, 1, 64)            0         
 1D)                                                             
                                                                 
 flatten_2 (Flatten)         (None, 64)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 65        
                                                                 
Total params: 257
Trainable params: 257
Non-trainable params: 0
_________________________________________________________________


In [10]:
model.compile(optimizer = "adam", loss = "mse")
model.fit(x, y, epochs = 100)

Epoch 1/100
1/1 [==============================] - 1s 977ms/step - loss: 21634.9336
Epoch 2/100
1/1 [==============================] - 0s 13ms/step - loss: 21030.9258
Epoch 3/100
1/1 [==============================] - 0s 10ms/step - loss: 20434.8652
Epoch 4/100
1/1 [==============================] - 0s 10ms/step - loss: 19846.9180
Epoch 5/100
1/1 [==============================] - 0s 13ms/step - loss: 19267.2441
Epoch 6/100
1/1 [==============================] - 0s 9ms/step - loss: 18695.9883
Epoch 7/100
1/1 [==============================] - 0s 17ms/step - loss: 18133.2871
Epoch 8/100
1/1 [==============================] - 0s 13ms/step - loss: 17579.2715
Epoch 9/100
1/1 [==============================] - 0s 11ms/step - loss: 17034.0527
Epoch 10/100
1/1 [==============================] - 0s 15ms/step - loss: 16499.6836
Epoch 11/100
1/1 [==============================] - 0s 11ms/step - loss: 15979.0918
Epoch 12/100
1/1 [==============================] - 0s 11ms/step - loss: 15476.0879
E

In [13]:
x_input = array([170, 180, 190])
x_input = x_input.reshape(1, steps, features)
y_pred = model.predict(x_input)
print(y_pred)

1/1 [==============================] - 0s 116ms/step
[[198.30017]]
